resolver: lts-20.1
packages:
  - .
extra-deps:
  - hashable-1.3.5.0
  - rest-rewrite-0.4.1
  - smtlib-backends-0.3
  - smtlib-backends-process-0.3
  - liquid-prelude-0.9.2.5
  - liquid-vector-0.12.3.1.2
  - liquidhaskell-0.9.2.5.0
  - liquidhaskell-boot-0.9.2.5.0
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: eb339f9abdf073f8d9f0c446c309006fdf49ed42

nix:
  packages: [cacert, git, hostname, z3]
